import type { ChangePlan, FileEdit } from "../types";

/** Build a PR body from the plan + concrete edits, following the spec template. */
export function buildPrBody(
  plan: ChangePlan,
  edits: FileEdit[],
  verification: { build: boolean; test: boolean; lint: boolean },
): string {
  const changes =
    edits.length > 0
      ? edits.map((e) => `- \`${e.file}\`: ${e.summary}`).join("\n")
      : "- (no changes)";

  const check = (ok: boolean) => (ok ? "x" : " ");

  return `## Summary

This PR applies a small maintenance change generated by codebase-gardener.

## Changes

${changes}

## Why this is safe

- The change is limited to low-risk maintenance work.
- No business logic or public API behavior was intentionally changed.
- The diff is intentionally small.

## Checks

- [${check(verification.build)}] Build passed
- [${check(verification.test)}] Tests passed
- [${check(verification.lint)}] Lint passed
- [ ] Manual review required

## Risk

Low

## Notes

Generated by codebase-gardener. Please review before merging.
`;
}
