import type { VerificationResult } from "../apply/applier";
import type { ChangePlan, FileEdit } from "../types";

/** Render a check line reflecting the actual verification state. */
function checkLine(label: string, state: "passed" | "failed" | "skipped"): string {
  if (state === "passed") return `- [x] ${label} passed`;
  if (state === "failed") return `- [ ] ${label} FAILED — needs attention`;
  return `- [ ] ${label} (not run locally; left for CI)`;
}

/** Build a PR body from the plan + concrete edits + verification results. */
export function buildPrBody(
  plan: ChangePlan,
  edits: FileEdit[],
  verification: VerificationResult,
): string {
  const changes =
    edits.length > 0
      ? edits.map((e) => `- \`${e.file}\`: ${e.summary}`).join("\n")
      : "- (no changes)";

  return `## Summary

This PR applies a small maintenance change generated by codebase-gardener.

## Changes

${changes}

## Why this is safe

- The change is limited to low-risk maintenance work.
- No business logic or public API behavior was intentionally changed.
- The diff is intentionally small.

## Checks

${checkLine("Lint", verification.lint)}
${checkLine("Tests", verification.test)}
- [ ] Manual review required

## Risk

Low

## Notes

Generated by codebase-gardener. Please review before merging.
`;
}
